//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelChina.AF.Test.DemoSV.Test.TransSVDirect {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.telchina.com.cn/TRF/V4/Service/2011/03", ConfigurationName="TransSVDirect.ITransSV")]
    public interface ITransSV {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/Required", ReplyAction="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiredResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Demo.DemoSV.Exceptions.ExpectedException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiredExpectedExcept" +
            "ionFault", Name="ExpectedException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Demo.DemoSV.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.UnhandledException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiredUnhandledExcep" +
            "tionFault", Name="UnhandledException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.ExceptionBase), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiredExceptionBaseF" +
            "ault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        System.Guid Required(bool isSucceed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiresNew", ReplyAction="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiresNewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.ExceptionBase), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiresNewExceptionBa" +
            "seFault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Demo.DemoSV.Exceptions.ExpectedException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiresNewExpectedExc" +
            "eptionFault", Name="ExpectedException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Demo.DemoSV.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.UnhandledException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/RequiresNewUnhandledEx" +
            "ceptionFault", Name="UnhandledException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        System.Guid RequiresNew(bool isSucceed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/NotSupported", ReplyAction="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/NotSupportedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Demo.DemoSV.Exceptions.ExpectedException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/NotSupportedExpectedEx" +
            "ceptionFault", Name="ExpectedException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Demo.DemoSV.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.UnhandledException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/NotSupportedUnhandledE" +
            "xceptionFault", Name="UnhandledException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.ExceptionBase), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/NotSupportedExceptionB" +
            "aseFault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        System.Guid NotSupported(bool isSucceed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/Supported", ReplyAction="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/SupportedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Demo.DemoSV.Exceptions.ExpectedException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/SupportedExpectedExcep" +
            "tionFault", Name="ExpectedException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Demo.DemoSV.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.UnhandledException), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/SupportedUnhandledExce" +
            "ptionFault", Name="UnhandledException", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(TelChina.AF.Sys.Exceptions.ExceptionBase), Action="http://www.telchina.com.cn/TRF/V4/Service/2011/03/ITransSV/SupportedExceptionBase" +
            "Fault", Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/TelChina.AF.Sys.Exceptions")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void Supported();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransSVChannel : TelChina.AF.Test.DemoSV.Test.TransSVDirect.ITransSV, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransSVClient : System.ServiceModel.ClientBase<TelChina.AF.Test.DemoSV.Test.TransSVDirect.ITransSV>, TelChina.AF.Test.DemoSV.Test.TransSVDirect.ITransSV {
        
        public TransSVClient() {
        }
        
        public TransSVClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransSVClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransSVClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransSVClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Required(bool isSucceed) {
            return base.Channel.Required(isSucceed);
        }
        
        public System.Guid RequiresNew(bool isSucceed) {
            return base.Channel.RequiresNew(isSucceed);
        }
        
        public System.Guid NotSupported(bool isSucceed) {
            return base.Channel.NotSupported(isSucceed);
        }
        
        public void Supported() {
            base.Channel.Supported();
        }
    }
}
