//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using TelChina.AF.Persistant;
using TelChina.AF.Sys.Serialization;
using System.Runtime.Serialization;
using System.Text;

namespace TelChina.AF.Demo
{

    public partial class Answer : EntityBase
    {
        public Answer()
        {

        }
        /// <summary>
        /// auto-generated:设置本实体上的字段默认值,应用开发扩展点
        /// </summary>
        protected override void SetDefaultValue()
        {

        }
        /// <summary>
        /// auto-generated:执行字段合法性检查,应用开发扩展点
        /// </summary>
        protected override void OnValidate()
        {

        }
        /// <summary>
        /// auto-generated:新增保存的前置条件
        /// </summary>
        protected override void OnInserting()
        {

        }
        /// <summary>
        /// auto-generated:新增保存的后置条件
        /// </summary>
        protected override void OnInserted()
        {

        }
        /// <summary>
        /// auto-generated:修改保存的前置条件
        /// </summary>
        protected override void OnUpdating()
        {

        }
        /// <summary>
        /// auto-generated:修改保存的后置条件
        /// </summary>
        protected override void OnUpdated()
        {

        }
        /// <summary>
        /// auto-generated:删除的前置条件
        /// </summary>
        protected override void OnDeleting()
        {

        }
        /// <summary>
        /// auto-generated:删除的后置条件
        /// </summary>
        protected override void OnDeleted()
        {

        }

        public override string ToString()
        {
            var result = new StringBuilder(128);
            result.Append(string.Format("EnitityType:{0},Propertys:[{1}:{2},{3}:{4}]", "Answer", "Name", this.Name,
                                        "Question", "Null"));
            result.Append(base.ToString());

            return result.ToString();
        }
        public virtual String GetName()
        {
            return this._name;
        }

        public virtual void test()
        {

        }

        public virtual Question XXX()
        {
            return this._xxx;
        }
    }
}


