//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Iesi.Collections.Generic;
using TelChina.AF.Persistant;

namespace TelChina.AF.Demo
{
    public partial class Question2 : EntityBase
    {
        private String _name;

        public virtual String Name
        {
            get
            {
                return this._name;
            }
            set
            {
                if (this._name != value)
                {
                    RaisPropertyChangIngEvent("Name");
                    _name = value;
                    RaisPropertyChangedEvent("Name");
                }
            }
        }

        private string entityComponet;

        public override string EntityComponent
        {
            get
            {
                return entityComponet;
            }
            set
            {
                this.entityComponet = value;
            }
        }


        private ISet<Answer2> _answers;

        /// <summary>
        /// 答案
        /// </summary>
        public virtual ISet<Answer2> Answers
        {
            get
            {
                if (_answers == null)
                {
                    _answers = new HashedSet<Answer2>();
                }
                return _answers;
            }
            set
            {
                _answers = value;
            }
        }
    }
}
