//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iesi.Collections.Generic;
using System;
using TelChina.AF.Persistant;

namespace TelChina.AF.Demo
{
    public partial class SystemResource : EntityBase
    {
        /// <summary>
        /// 类名称
        /// </summary>
        private string _className;

        /// <summary>
        /// 列名称
        /// </summary>
        private string _columnName;

        /// <summary>
        /// 列描述
        /// </summary>
        private string _columnDescribe;

        /// <summary>
        /// 是否可见
        /// </summary>
        private bool? _isVisible;

        /// <summary>
        /// 类名称
        /// </summary>
        public virtual string ClassName
        {
            get
            {
                return this._className;
            }
            set
            {
                if (this._className != value)
                {
                    RaisPropertyChangIngEvent("ClassName");
                    _className = value;
                    RaisPropertyChangedEvent("ClassName");
                }
            }
        }

        /// <summary>
        /// 列名称
        /// </summary>
        public virtual string ColumnName
        {
            get
            {
                return this._columnName;
            }
            set
            {
                if (this._columnName != value)
                {
                    RaisPropertyChangIngEvent("ColumnName");
                    _columnName = value;
                    RaisPropertyChangedEvent("ColumnName");
                }
            }
        }

        /// <summary>
        /// 列描述
        /// </summary>
        public virtual string ColumnDescribe
        {
            get
            {
                return this._columnDescribe;
            }
            set
            {
                if (this._columnDescribe != value)
                {
                    RaisPropertyChangIngEvent("ColumnDescribe");
                    _columnDescribe = value;
                    RaisPropertyChangedEvent("ColumnDescribe");
                }
            }
        }

        /// <summary>
        /// 是否可见
        /// </summary>
        public virtual bool? IsVisible
        {
            get
            {
                return this._isVisible;
            }
            set
            {
                if (this._isVisible != value)
                {
                    RaisPropertyChangIngEvent("IsVisible");
                    _isVisible = value;
                    RaisPropertyChangedEvent("IsVisible");
                }
            }
        }


        private string entityComponet;

        public override string EntityComponent
        {
            get
            {
                return entityComponet;
            }
            set
            {
                this.entityComponet = value;
            }
        }

    }
}


