//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using TelChina.AF.Persistant;

namespace TelChina.AF.Demo
{
    public partial class Answer3 : EntityBase
    {
    }
}
