//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using TelChina.AF.Persistant;

namespace TelChina.AF.Demo
{
	public partial class Answer : EntityBase
	{
	 	/// <summary>
	    /// auto-generated:设置本实体上的字段默认值,应用开发扩展点
	    /// </summary>
	    protected override void SetDefaultValue()
	    {
	        
	    }
		/// <summary>
	    /// auto-generated:执行字段合法性检查,应用开发扩展点
	    /// </summary>
	    protected override void OnValidate()
	    {
	       
	    }
		/// <summary>
	    /// auto-generated:新增保存的前置条件
	    /// </summary>
	    protected override void OnInserting()
	    {
	        
	    }
	 	/// <summary>
	    /// auto-generated:新增保存的后置条件
	    /// </summary>
	    protected override void OnInserted()
	    {
	       
	    }
		/// <summary>
	    /// auto-generated:修改保存的前置条件
	    /// </summary>
	    protected override void OnUpdating()
	    {
	        
	    }
		/// <summary>
	    /// auto-generated:修改保存的后置条件
	    /// </summary>
	    protected override void OnUpdated()
	    {
	       
	    }
		/// <summary>
	    /// auto-generated:删除的前置条件
	    /// </summary>
	    protected override void OnDeleting()
	    {
	        
	    }
		/// <summary>
	    /// auto-generated:删除的后置条件
	    /// </summary>
		protected override void OnDeleted()
	    {
	       
	    }
	}
}


